// ⚠️ DEMO MODE 전용 가상(SAMPLE) 뉴스입니다. 실제 기사·실제 보도가 아닙니다.
// 언론사명은 모두 가상의 이름이며, 링크는 example.com 으로 연결됩니다.
// scores 는 '가상의 AI 평가' 값이고, 종합점수(total)와 순위(rank)는
// config/scoring.json 의 가중치로 scripts/build-demo.mjs 가 계산합니다.

export const briefingMeta = {
  headline:
    '자율주행 상용화 경쟁이 빨라지면서 사고책임과 자동차보험 체계 개편 논의가 본격화되고, 보험업계는 생성형 AI를 상담·심사 현장에 빠르게 도입하고 있습니다.',
  keywords: ['자율주행', 'AI Agent', '자동차보험', '로보택시', '전기차'],
  issues: [
    {
      id: 'issue-av',
      title: '자율주행 상용화 경쟁 가속',
      summary:
        '로보택시 서비스 지역 확대와 국내 시범운행지구 추가 지정이 이어지는 가운데, 사고 시 책임을 누가 지는지에 대한 제도 논의가 함께 진행되고 있습니다.',
      articleIds: ['auto-01', 'mob-01', 'mob-03', 'ai-05'],
    },
    {
      id: 'issue-genai-ins',
      title: '보험업계 생성형 AI 도입 확대',
      summary:
        '보험사들이 고객 상담·보험금 심사에 생성형 AI와 AI Agent를 적용하는 사례가 늘고 있으며, 운전 데이터 기반 상품 등 데이터 활용도 넓어지고 있습니다.',
      articleIds: ['ins-01', 'ai-01', 'auto-04'],
    },
    {
      id: 'issue-ev',
      title: '전기차 정책·수리비 구조 변화',
      summary:
        '충전 인프라 확충 정책과 함께 전기차 배터리 수리 기준 정비가 논의되면서 자동차보험 손해율에도 영향을 줄 수 있는 변화가 나타나고 있습니다.',
      articleIds: ['auto-05', 'mob-05', 'auto-02'],
    },
  ],
};

export const articles = [
  // ───────────────── 🚗 자동차보험 ─────────────────
  {
    id: 'auto-01',
    category: 'auto',
    title: '자율주행차 사고 책임 분담 기준 마련 논의 본격화',
    source: '샘플경제신문',
    hoursAgo: 3,
    lang: 'ko',
    coverage: 4,
    keywords: ['자율주행', '사고책임', '자동차보험 제도'],
    scores: { importance: 95, relevance: 98, recency: 92, impact: 96, novelty: 84 },
    oneLiner: '자율주행 중 사고가 났을 때 운전자·제조사·보험사 간 책임을 어떻게 나눌지에 대한 제도 논의가 시작됐다.',
    summary3: [
      '관계 부처와 업계가 자율주행 단계별 사고 책임 기준을 논의하는 협의체를 구성했다.',
      '현행 자동차보험 체계에서 운전자 중심 책임 구조를 어떻게 보완할지가 핵심 쟁점이다.',
      '사고기록장치(EDR) 등 데이터 접근 권한 문제도 함께 다뤄질 예정이다.',
    ],
    keyPoints: [
      '협의체 구성: 정부·완성차·보험업계 참여',
      '쟁점 1: 자율주행 레벨별 운전자 책임 범위',
      '쟁점 2: 제조사 결함 시 보험사의 구상권 행사 절차',
      '쟁점 3: 사고 원인 규명을 위한 주행 데이터 공유',
    ],
    whyImportant:
      '자율주행 사고의 책임 구조는 자동차보험 상품 설계, 보험료 산정, 보상 절차 전반을 바꿀 수 있는 근본적인 제도 이슈이기 때문에 선정했습니다.',
    perspective:
      '책임이 제조사 쪽으로 일부 이동하면 개인 자동차보험의 담보 구성과 제조물책임보험 수요가 함께 변할 수 있습니다. 보험사 입장에서는 사고 데이터 접근권 확보가 손해사정 역량의 핵심이 될 가능성이 있습니다. (기사에 구체적 제도안은 아직 제시되지 않았습니다.)',
    watchNext: ['협의체의 1차 논의 결과 발표 시점', '사고기록 데이터 공유 범위에 대한 업계 입장', '해외(미국·독일 등) 제도와의 비교 자료'],
  },
  {
    id: 'auto-02',
    category: 'auto',
    title: '자동차보험 손해율 상승세…보험료 조정 검토 목소리',
    source: '데모보험일보',
    hoursAgo: 6,
    lang: 'ko',
    coverage: 3,
    keywords: ['손해율', '보험료', '자동차보험'],
    scores: { importance: 90, relevance: 97, recency: 85, impact: 88, novelty: 62 },
    oneLiner: '주요 손해보험사의 자동차보험 손해율이 오르면서 내년 보험료 조정 필요성이 업계에서 거론되고 있다.',
    summary3: [
      '최근 몇 달간 주요 손보사의 자동차보험 손해율이 적정 수준을 웃도는 흐름을 보였다.',
      '정비요금·부품비 상승과 사고 건수 변화가 원인으로 언급됐다.',
      '업계 일부에서 보험료 조정 검토 의견이 나오지만 결정된 사항은 없다.',
    ],
    keyPoints: ['손해율 상승 추세가 이어짐', '원인: 정비요금·부품비·사고 건수', '보험료 조정은 검토 단계이며 확정되지 않음'],
    whyImportant: '손해율은 자동차보험 수익성과 보험료 수준을 결정하는 핵심 지표이므로 업무 연관도가 매우 높아 선정했습니다.',
    perspective:
      '손해율 흐름이 이어지면 보험료 조정 논의와 함께 할인 특약 구조 재검토가 이어질 수 있습니다. 다만 보험료는 금융당국과의 협의가 필요한 사안이어서 실제 조정 여부는 지켜봐야 합니다.',
    watchNext: ['연말 손해율 집계 결과', '금융당국의 보험료 관련 입장', '정비요금 협상 동향'],
  },
  {
    id: 'auto-03',
    category: 'auto',
    title: '경미사고 과잉진료 막는다…경상환자 보상 제도 개선안 공개',
    source: '샘플데일리',
    hoursAgo: 9,
    lang: 'ko',
    coverage: 2,
    keywords: ['보험사기', '경상환자', '제도개선'],
    scores: { importance: 84, relevance: 95, recency: 80, impact: 82, novelty: 70 },
    oneLiner: '경미한 교통사고 후 장기 치료가 반복되는 문제를 줄이기 위한 보상 제도 개선안이 공개됐다.',
    summary3: [
      '경상환자의 장기 치료 시 진단서 등 추가 근거를 요구하는 방안이 포함됐다.',
      '과잉진료와 보험사기로 인한 보험료 인상 압력을 줄이는 것이 목적이다.',
      '의료계와 소비자 단체의 의견 수렴 절차가 남아 있다.',
    ],
    keyPoints: ['대상: 경미사고 경상환자 치료', '방향: 장기 치료 시 추가 근거 요구', '향후: 이해관계자 의견 수렴'],
    whyImportant: '보험사기·과잉진료는 자동차보험 손해율과 직결되는 문제로, 제도 변화 시 보상 실무에 바로 영향이 있어 선정했습니다.',
    perspective:
      '개선안이 시행되면 보상 담당 부서의 심사 기준과 안내 절차가 바뀔 수 있습니다. 소비자 보호와의 균형이 쟁점이 될 수 있어 최종안 내용을 확인할 필요가 있습니다.',
    watchNext: ['의견 수렴 결과와 최종안', '시행 시기', '의료계 반응'],
  },
  {
    id: 'auto-04',
    category: 'auto',
    title: '커넥티드카 데이터로 운전습관 연계 보험(UBI) 확대',
    source: 'Sample Auto Wire',
    originalTitle: 'Insurers expand usage-based policies using connected car data',
    hoursAgo: 12,
    lang: 'en',
    coverage: 2,
    keywords: ['UBI', '커넥티드카', '보험상품'],
    scores: { importance: 80, relevance: 92, recency: 78, impact: 84, novelty: 76 },
    oneLiner: '해외 보험사들이 차량에서 직접 수집한 주행 데이터를 활용한 운전습관 연계 보험을 늘리고 있다.',
    summary3: [
      '별도 단말기 없이 차량 내장 통신 데이터를 활용하는 방식이 늘고 있다.',
      '급가속·급제동·야간 운행 등이 보험료 산정 요소로 쓰인다.',
      '개인정보 동의 절차와 데이터 정확성이 과제로 거론됐다.',
    ],
    keyPoints: ['데이터 출처: 차량 내장 통신(커넥티드카)', '평가 요소: 운전 행태', '과제: 개인정보 동의·데이터 품질'],
    whyImportant: '자동차보험 요율 산정 방식의 변화를 보여주는 해외 동향으로, 국내 상품 개발 방향에 참고가 될 수 있어 선정했습니다.',
    perspective:
      '국내에서도 완성차 데이터와 보험의 결합이 늘어날 경우 제휴 구조와 데이터 이용 동의가 핵심 경쟁 요소가 될 수 있습니다. 기사는 해외 사례이므로 국내 적용 가능성은 별도로 확인이 필요합니다.',
    watchNext: ['국내 완성차-보험사 데이터 제휴 사례', '개인정보 관련 규제 해석'],
  },
  {
    id: 'auto-05',
    category: 'auto',
    title: '전기차 수리비 부담에 배터리 부분수리 기준 정비 논의',
    source: '가상모빌리티타임즈',
    hoursAgo: 15,
    lang: 'ko',
    coverage: 3,
    keywords: ['전기차', '수리비', '배터리'],
    scores: { importance: 82, relevance: 90, recency: 76, impact: 85, novelty: 68 },
    oneLiner: '경미한 손상에도 배터리 전체를 교체하는 관행을 줄이기 위해 부분수리 기준을 마련하자는 논의가 진행 중이다.',
    summary3: [
      '전기차 사고 시 배터리 팩 전체 교체로 수리비가 커지는 사례가 언급됐다.',
      '손상 정도에 따른 부분수리·재사용 기준이 필요하다는 의견이 나왔다.',
      '안전성 검증 방법이 함께 논의되고 있다.',
    ],
    keyPoints: ['문제: 배터리 전체 교체로 인한 고액 수리비', '대안: 부분수리 및 재사용 기준', '전제: 안전성 검증 체계'],
    whyImportant: '전기차 비중이 늘수록 수리비 구조가 자동차보험 손해율에 미치는 영향이 커지므로 선정했습니다.',
    perspective:
      '부분수리 기준이 마련되면 전기차 사고의 평균 수리비가 낮아질 여지가 있습니다. 보험사는 손해사정 기준과 협력 정비망 역량을 함께 점검할 필요가 있습니다.',
    watchNext: ['부분수리 기준안 공개 여부', '제조사 보증 정책 변화'],
  },

  // ───────────────── 🚘 모빌리티 ─────────────────
  {
    id: 'mob-01',
    category: 'mobility',
    title: 'Waymo, 로보택시 서비스 지역 추가 확대 계획 밝혀',
    source: 'Sample Auto Wire',
    originalTitle: 'Waymo outlines plans to bring robotaxi service to more cities',
    hoursAgo: 4,
    lang: 'en',
    coverage: 5,
    keywords: ['Waymo', '로보택시', '자율주행'],
    scores: { importance: 94, relevance: 88, recency: 92, impact: 93, novelty: 80 },
    oneLiner: '(가상 기사) Waymo가 로보택시 운영 도시를 추가로 늘리겠다는 계획을 밝혔다는 시나리오.',
    summary3: [
      '로보택시 서비스 지역을 신규 도시로 넓히는 계획이 소개됐다.',
      '지역별 규제 승인과 현지 운영 파트너 확보가 전제 조건으로 언급됐다.',
      '구체적인 일정은 도시별로 다르며 확정되지 않았다.',
    ],
    keyPoints: ['내용: 서비스 지역 확대 계획', '전제: 지역별 규제 승인', '일정: 미확정'],
    whyImportant: '로보택시 상용 서비스의 확산 속도는 자율주행 산업 전체의 시장 형성 시점을 가늠하는 지표이기 때문에 선정했습니다.',
    perspective:
      '무인 차량 운행이 늘수록 운행사 단위의 대규모 배상책임 보험 수요가 커질 수 있습니다. 개인 운전자 중심의 기존 보험과는 다른 상품 구조가 필요할 수 있다는 점에서 관찰 가치가 있습니다.',
    watchNext: ['신규 도시의 규제 승인 결과', '운영 중 사고 통계 공개 여부'],
  },
  {
    id: 'mob-02',
    category: 'mobility',
    title: '완성차 업계, SDV 전환 위해 소프트웨어 조직 강화',
    source: '샘플IT뉴스',
    hoursAgo: 10,
    lang: 'ko',
    coverage: 3,
    keywords: ['SDV', '완성차', '소프트웨어'],
    scores: { importance: 85, relevance: 76, recency: 78, impact: 86, novelty: 72 },
    oneLiner: '완성차 업체들이 소프트웨어 중심 자동차(SDV) 전환을 위해 개발 조직과 인력을 확대하고 있다.',
    summary3: [
      '여러 완성차 업체가 SDV 전담 조직을 신설하거나 확대했다.',
      '무선 업데이트(OTA)로 기능을 추가하는 구조가 핵심이다.',
      '외부 소프트웨어 기업과의 협력도 늘고 있다.',
    ],
    keyPoints: ['SDV 전담 조직 확대', '핵심 기술: OTA 무선 업데이트', '외부 협력 증가'],
    whyImportant: '차량 기능이 소프트웨어로 바뀌는 흐름은 차량 가치·안전·데이터 구조를 바꾸는 중장기 변화여서 선정했습니다.',
    perspective:
      'OTA로 안전 기능이 바뀌면 차량의 위험도가 출고 이후에도 달라질 수 있습니다. 보험 관점에서는 차량 위험 평가를 고정값이 아닌 동적 정보로 다뤄야 할 가능성이 있습니다.',
    watchNext: ['OTA 업데이트 관련 안전 규정', '차량 데이터 개방 정책'],
  },
  {
    id: 'mob-03',
    category: 'mobility',
    title: '국내 레벨4 자율주행 시범운행지구 추가 지정',
    source: '샘플경제신문',
    hoursAgo: 7,
    lang: 'ko',
    coverage: 4,
    keywords: ['자율주행', '시범운행지구', '정책'],
    scores: { importance: 88, relevance: 90, recency: 88, impact: 87, novelty: 74 },
    oneLiner: '레벨4 자율주행 서비스를 시험할 수 있는 시범운행지구가 추가로 지정됐다.',
    summary3: [
      '신규 지구에서는 유상 여객·화물 운송 실증이 가능해진다.',
      '참여 기업은 안전요원 탑승 등 운영 조건을 따라야 한다.',
      '실증 데이터는 향후 제도 정비에 활용될 예정이다.',
    ],
    keyPoints: ['시범운행지구 추가 지정', '유상 운송 실증 허용', '실증 데이터의 제도 반영'],
    whyImportant: '국내 자율주행 상용화 일정과 직결되는 정책 결정이어서 선정했습니다.',
    perspective:
      '시범운행 차량은 별도의 보험 가입 요건이 적용되는 경우가 많아, 실증 확대는 관련 보험 수요 증가로 이어질 수 있습니다. 사고 데이터가 쌓이면 요율 산정 근거로 활용될 여지도 있습니다.',
    watchNext: ['지구별 참여 기업 명단', '실증 운행 중 사고 처리 기준'],
  },
  {
    id: 'mob-04',
    category: 'mobility',
    title: 'UAM 실증 2단계 착수…도심항공교통 상용화 준비',
    source: '가상모빌리티타임즈',
    hoursAgo: 20,
    lang: 'ko',
    coverage: 2,
    keywords: ['UAM', '미래교통', '실증'],
    scores: { importance: 78, relevance: 70, recency: 72, impact: 80, novelty: 74 },
    oneLiner: '도심항공교통(UAM) 실증이 도심 구간을 포함하는 2단계로 넘어갔다.',
    summary3: [
      '2단계 실증은 도심 인접 구간 비행을 포함한다.',
      '소음·안전·관제 체계 검증이 주요 과제다.',
      '상용화 시점은 실증 결과에 따라 결정될 예정이다.',
    ],
    keyPoints: ['실증 2단계 착수', '검증 항목: 소음·안전·관제', '상용화 시점 미정'],
    whyImportant: '미래 교통수단의 상용화 진행 상황을 보여주는 정책 이정표여서 선정했습니다.',
    perspective:
      'UAM은 항공보험과 자동차보험의 경계에 있는 영역이라 새로운 담보 설계가 필요할 수 있습니다. 다만 상용화까지는 시간이 남아 있어 단기 영향은 제한적입니다.',
    watchNext: ['실증 결과 발표', 'UAM 보험 의무가입 기준 논의'],
  },
  {
    id: 'mob-05',
    category: 'mobility',
    title: '전기차 충전 인프라 확충 정책 발표…아파트 충전기 확대',
    source: '샘플데일리',
    hoursAgo: 18,
    lang: 'ko',
    coverage: 3,
    keywords: ['전기차', '충전인프라', '정책'],
    scores: { importance: 80, relevance: 72, recency: 75, impact: 78, novelty: 60 },
    oneLiner: '공동주택을 중심으로 전기차 충전기를 늘리는 인프라 확충 정책이 발표됐다.',
    summary3: [
      '공동주택 충전기 설치 지원을 확대하는 내용이 담겼다.',
      '지하주차장 충전 시설 안전 기준 강화도 포함됐다.',
      '지자체별 세부 시행 계획이 뒤따를 예정이다.',
    ],
    keyPoints: ['공동주택 충전기 지원 확대', '지하주차장 안전 기준 강화', '지자체 세부 계획 예정'],
    whyImportant: '전기차 보급 속도와 충전 시설 안전 문제를 동시에 다루는 정책이어서 선정했습니다.',
    perspective:
      '충전 시설 안전 기준 강화는 화재보험·재물보험의 위험 평가에도 참고가 될 수 있습니다. 전기차 보급 확대는 장기적으로 자동차보험 차종 구성 변화로 이어집니다.',
    watchNext: ['지자체 시행 계획', '충전시설 화재 안전 기준 세부안'],
  },

  // ───────────────── 🏦 보험 ─────────────────
  {
    id: 'ins-01',
    category: 'insurance',
    title: '보험업계, 생성형 AI 상담·보험금 심사 도입 확대',
    source: '데모금융신문',
    hoursAgo: 5,
    lang: 'ko',
    coverage: 4,
    keywords: ['생성형 AI', '보험업계', 'AI Agent'],
    scores: { importance: 92, relevance: 95, recency: 88, impact: 92, novelty: 78 },
    oneLiner: '보험사들이 고객 상담과 보험금 심사 업무에 생성형 AI를 적용하는 사례가 늘고 있다.',
    summary3: [
      '여러 보험사가 상담 챗봇과 내부 업무 보조에 생성형 AI를 도입했다.',
      '보험금 심사 서류 검토 자동화도 시범 적용 단계에 있다.',
      '설명 가능성과 개인정보 보호가 과제로 지적됐다.',
    ],
    keyPoints: ['적용 분야: 상담, 서류 검토, 내부 업무', '단계: 일부 시범 적용', '과제: 설명 가능성·개인정보'],
    whyImportant: '보험 업무 방식 자체를 바꾸는 기술 도입 흐름으로, 업무 연관도와 영향도가 모두 높아 선정했습니다.',
    perspective:
      '심사 자동화가 확대되면 처리 속도는 빨라질 수 있지만 오류 책임과 소비자 설명 의무 문제가 함께 커집니다. 금융당국의 AI 활용 가이드라인과 함께 보는 것이 좋습니다.',
    watchNext: ['금융권 AI 가이드라인 개정', '보험금 심사 AI의 오류 사례 및 대응'],
  },
  {
    id: 'ins-02',
    category: 'insurance',
    title: '금융당국, 보험사 건전성 규제 보완 방안 예고',
    source: '데모보험일보',
    hoursAgo: 8,
    lang: 'ko',
    coverage: 3,
    keywords: ['금융당국', '건전성', 'K-ICS'],
    scores: { importance: 90, relevance: 88, recency: 84, impact: 90, novelty: 64 },
    oneLiner: '금융당국이 보험사 지급여력 제도(K-ICS) 운영과 관련한 보완 방안을 예고했다.',
    summary3: [
      '지급여력 비율 산정 방식 일부를 보완하는 방안이 언급됐다.',
      '보험사별 자본 관리 전략에 영향을 줄 수 있다.',
      '세부 내용은 업계 의견 수렴 후 확정될 예정이다.',
    ],
    keyPoints: ['대상: 지급여력(K-ICS) 제도', '영향: 자본 관리 전략', '절차: 의견 수렴 후 확정'],
    whyImportant: '건전성 규제는 보험사의 상품 전략·배당·자본 조달에 모두 영향을 주는 핵심 정책이어서 선정했습니다.',
    perspective:
      '보완 내용에 따라 보험사들의 상품 포트폴리오 조정이 이어질 수 있습니다. 기사에는 구체적 수치가 없으므로 최종안 발표를 확인해야 합니다.',
    watchNext: ['최종안 발표 일정', '보험사별 지급여력비율 공시'],
  },
  {
    id: 'ins-03',
    category: 'insurance',
    title: '인슈어테크, 커머스·모빌리티 플랫폼과 임베디드 보험 제휴 확대',
    source: '샘플IT뉴스',
    hoursAgo: 14,
    lang: 'ko',
    coverage: 2,
    keywords: ['InsurTech', '임베디드보험', '플랫폼'],
    scores: { importance: 76, relevance: 84, recency: 74, impact: 78, novelty: 80 },
    oneLiner: '구매·이동 과정에 보험을 자연스럽게 결합하는 임베디드 보험 제휴가 늘고 있다.',
    summary3: [
      '커머스·모빌리티 플랫폼에서 결제 단계에 보험을 결합하는 사례가 늘었다.',
      '소액·단기 보험이 주로 활용된다.',
      '불완전판매 방지를 위한 안내 방식이 과제로 꼽혔다.',
    ],
    keyPoints: ['결합 지점: 결제·이용 단계', '상품 형태: 소액·단기', '과제: 판매 안내 적정성'],
    whyImportant: '보험 판매 채널이 플랫폼으로 이동하는 흐름을 보여주는 사례여서 선정했습니다.',
    perspective:
      '모빌리티 플랫폼과 결합된 단기 운전자보험·렌터카 보험은 자동차보험 영역과도 맞닿아 있습니다. 채널 제휴 경쟁이 심해질 수 있다는 점에 주목할 만합니다.',
    watchNext: ['플랫폼 보험 판매 규제 정비', '주요 제휴 사례'],
  },
  {
    id: 'ins-04',
    category: 'insurance',
    title: '기후 재해 손실 확대로 글로벌 재보험 비용 상승 우려',
    source: 'Demo Insurance Review',
    originalTitle: 'Climate losses push up global reinsurance costs',
    hoursAgo: 22,
    lang: 'en',
    coverage: 3,
    keywords: ['기후리스크', '재보험', '자연재해'],
    scores: { importance: 82, relevance: 78, recency: 70, impact: 84, novelty: 58 },
    oneLiner: '자연재해 손실이 늘면서 원수보험사가 부담하는 재보험 비용이 오를 수 있다는 전망이 나왔다.',
    summary3: [
      '자연재해 손실 증가가 재보험 시장 가격에 반영되고 있다.',
      '재보험 갱신 시점에 조건이 까다로워질 수 있다는 관측이 있다.',
      '원수보험사의 재물보험 요율에도 영향이 있을 수 있다.',
    ],
    keyPoints: ['원인: 자연재해 손실 확대', '영향: 재보험 갱신 조건', '파급: 재물보험 요율'],
    whyImportant: '재보험 비용은 손해보험사 전반의 원가에 영향을 주는 글로벌 변수여서 선정했습니다.',
    perspective:
      '침수 차량 등 자연재해 관련 자동차보험 손해에도 간접적으로 연결될 수 있습니다. 다만 기사는 글로벌 시장 전망이므로 국내 영향은 별도 확인이 필요합니다.',
    watchNext: ['연초 재보험 갱신 결과', '국내 손보사 재보험 비용 공시'],
  },
  {
    id: 'ins-05',
    category: 'insurance',
    title: '실손보험 개편 논의 재점화…비급여 관리 방안 쟁점',
    source: '데모금융신문',
    hoursAgo: 16,
    lang: 'ko',
    coverage: 3,
    keywords: ['실손보험', '비급여', '제도개편'],
    scores: { importance: 86, relevance: 80, recency: 74, impact: 86, novelty: 56 },
    oneLiner: '실손보험 손해율 문제와 관련해 비급여 진료 관리 방안을 중심으로 개편 논의가 다시 이어지고 있다.',
    summary3: [
      '비급여 진료 관리가 개편 논의의 핵심 쟁점으로 다시 부각됐다.',
      '보험업계와 의료계의 입장 차가 여전하다.',
      '구체적인 개편 일정은 제시되지 않았다.',
    ],
    keyPoints: ['쟁점: 비급여 관리', '이해관계: 보험업계 vs 의료계', '일정: 미정'],
    whyImportant: '실손보험은 가입자가 많은 대표 상품이라 제도 변화의 파급력이 커서 선정했습니다.',
    perspective:
      '실손보험 논의는 자동차보험 경상환자 치료비 문제와 구조적으로 비슷한 측면이 있어 함께 보면 좋습니다. 개편안이 구체화되기 전까지는 방향성만 확인하는 것이 적절합니다.',
    watchNext: ['정부 개편안 발표 여부', '의료계 공식 입장'],
  },

  // ───────────────── 🤖 AI 기술 ─────────────────
  {
    id: 'ai-01',
    category: 'ai',
    title: 'AI Agent, 기업 업무 자동화 본격 도입 단계로',
    source: 'Demo Tech Journal',
    originalTitle: 'AI agents move from pilots to production in enterprise workflows',
    hoursAgo: 4,
    lang: 'en',
    coverage: 5,
    keywords: ['AI Agent', '업무자동화', '엔터프라이즈'],
    scores: { importance: 93, relevance: 82, recency: 90, impact: 94, novelty: 78 },
    oneLiner: '스스로 여러 단계를 수행하는 AI Agent가 기업 현장에서 시범 단계를 넘어 실제 업무에 쓰이기 시작했다.',
    summary3: [
      '기업들이 AI Agent를 문서 처리·고객 응대 등 실제 업무 흐름에 연결하고 있다.',
      '사람의 승인 단계를 두는 방식이 일반적이다.',
      '보안·권한 관리가 도입의 주요 과제로 꼽혔다.',
    ],
    keyPoints: ['단계: 시범 → 실제 운영', '운영 방식: 사람 승인 포함', '과제: 보안·권한 관리'],
    whyImportant: 'AI Agent는 보험사 백오피스 업무에도 바로 적용 가능한 기술이어서 영향도가 높다고 판단해 선정했습니다.',
    perspective:
      '보험 청구 접수, 서류 확인, 고객 안내처럼 반복적인 다단계 업무가 우선 적용 대상이 될 수 있습니다. 오류 시 책임 소재와 감사 기록 관리 체계가 함께 필요합니다.',
    watchNext: ['금융권 AI Agent 도입 사례', 'AI Agent 보안 표준 논의'],
  },
  {
    id: 'ai-02',
    category: 'ai',
    title: '멀티모달 LLM 신모델 잇따라 공개…이미지·음성 이해 강화',
    source: '샘플IT뉴스',
    hoursAgo: 11,
    lang: 'ko',
    coverage: 4,
    keywords: ['LLM', '멀티모달', '생성형 AI'],
    scores: { importance: 88, relevance: 66, recency: 84, impact: 84, novelty: 72 },
    oneLiner: '텍스트뿐 아니라 이미지·음성을 함께 이해하는 멀티모달 대형언어모델이 잇따라 공개됐다.',
    summary3: [
      '여러 AI 기업이 멀티모달 기능을 강화한 신모델을 발표했다.',
      '문서·사진을 함께 해석하는 성능 개선이 강조됐다.',
      '실제 업무 정확도는 활용 분야별 검증이 필요하다.',
    ],
    keyPoints: ['이미지·음성·텍스트 통합 이해', '문서+사진 해석 성능 강조', '분야별 검증 필요'],
    whyImportant: '사진·문서를 함께 해석하는 능력은 사고 사진 분석 등 실무 활용 가능성이 있어 선정했습니다.',
    perspective:
      '사고 차량 사진과 견적서를 함께 분석하는 손해사정 보조에 응용될 여지가 있습니다. 다만 발표 자료의 성능 수치는 실제 환경과 다를 수 있어 자체 검증이 필요합니다.',
    watchNext: ['독립 기관의 성능 평가', '국내 서비스 출시 여부'],
  },
  {
    id: 'ai-03',
    category: 'ai',
    title: 'Physical AI 부상…로봇 학습용 시뮬레이션 경쟁 가열',
    source: 'Demo Tech Journal',
    originalTitle: 'Physical AI race heats up as robot simulation platforms expand',
    hoursAgo: 13,
    lang: 'en',
    coverage: 3,
    keywords: ['Physical AI', '로봇', '시뮬레이션'],
    scores: { importance: 86, relevance: 64, recency: 80, impact: 86, novelty: 84 },
    oneLiner: '현실 세계에서 움직이는 로봇을 위한 Physical AI 개발 경쟁이 시뮬레이션 플랫폼을 중심으로 커지고 있다.',
    summary3: [
      '가상 환경에서 로봇을 학습시키는 시뮬레이션 플랫폼 경쟁이 치열해졌다.',
      '물류·제조 현장이 초기 적용 분야로 꼽힌다.',
      '현실 적용 시 안전성 검증이 과제로 남아 있다.',
    ],
    keyPoints: ['핵심: 시뮬레이션 기반 학습', '초기 적용: 물류·제조', '과제: 현실 안전성'],
    whyImportant: 'Physical AI는 자율주행과 기술 기반을 공유하는 분야로, 중장기 산업 영향이 커 선정했습니다.',
    perspective:
      '로봇이 사람과 같은 공간에서 일하게 되면 새로운 배상책임 위험이 생깁니다. 자율주행 보험 논의와 유사한 구조의 상품 수요가 생길 수 있습니다.',
    watchNext: ['로봇 안전 인증 기준', '물류 현장 도입 사례'],
  },
  {
    id: 'ai-04',
    category: 'ai',
    title: 'AI 기본법 하위법령 논의…고영향 AI 판단 기준 쟁점',
    source: '샘플경제신문',
    hoursAgo: 19,
    lang: 'ko',
    coverage: 3,
    keywords: ['AI 규제', '고영향 AI', '정책'],
    scores: { importance: 87, relevance: 80, recency: 72, impact: 88, novelty: 62 },
    oneLiner: 'AI 관련 법령의 세부 기준을 정하는 과정에서 어떤 AI를 고영향 AI로 볼지가 쟁점이 되고 있다.',
    summary3: [
      '고영향 AI의 판단 기준과 사업자 의무가 주요 논의 대상이다.',
      '금융·의료 등 분야별 적용 방식에 대한 의견이 나뉜다.',
      '업계는 기준의 명확성을 요구하고 있다.',
    ],
    keyPoints: ['쟁점: 고영향 AI 기준', '분야별 적용 방식 이견', '업계 요구: 명확한 기준'],
    whyImportant: '보험 심사·요율 산정에 AI를 쓰는 경우 규제 대상이 될 수 있어 업무 연관도가 높다고 보고 선정했습니다.',
    perspective:
      '보험금 지급이나 가입 심사처럼 개인에게 중대한 영향을 주는 AI는 고영향 AI 논의 대상이 될 가능성이 있습니다. 확정된 기준이 아니므로 최종 하위법령을 확인해야 합니다.',
    watchNext: ['하위법령 최종안', '금융 분야 별도 가이드라인'],
  },
  {
    id: 'ai-05',
    category: 'ai',
    title: '온디바이스 AI 칩 경쟁, 차량용으로 확산',
    source: '가상모빌리티타임즈',
    hoursAgo: 9,
    lang: 'ko',
    coverage: 2,
    keywords: ['온디바이스 AI', '차량용 반도체', 'SDV'],
    scores: { importance: 82, relevance: 74, recency: 82, impact: 82, novelty: 76 },
    oneLiner: '클라우드 없이 기기 안에서 AI를 돌리는 칩 경쟁이 스마트폰을 넘어 자동차로 넓어지고 있다.',
    summary3: [
      '반도체 기업들이 차량용 AI 칩 라인업을 강화하고 있다.',
      '자율주행·운전자 보조·차량 내 음성비서가 주 용도다.',
      '전력 효율과 발열이 핵심 경쟁 요소다.',
    ],
    keyPoints: ['차량용 AI 칩 경쟁', '용도: 자율주행·ADAS·음성비서', '경쟁 요소: 전력 효율'],
    whyImportant: '차량 내 AI 연산 능력은 자율주행 수준과 직결되어 모빌리티 산업 변화를 이해하는 데 중요해 선정했습니다.',
    perspective:
      '차량 자체의 판단 능력이 높아질수록 사고 원인 분석에서 소프트웨어 판단 기록의 중요성이 커집니다. 보험 손해사정에서 데이터 해석 역량이 필요해질 수 있습니다.',
    watchNext: ['차량용 AI 칩 탑재 차종', '자율주행 소프트웨어 안전 인증'],
  },
];

// 최근 14일 키워드 등장 횟수 (트렌드 시연용 가상 통계)
// offset: 오늘 기준 며칠 전인지 (-13 ~ 0). 앱이 열릴 때 실제 날짜로 변환됩니다.
// [이전 7일 합계, 최근 7일 합계] 를 기준으로 날짜별로 나눠 생성합니다.
export const keywordTotals = {
  자율주행: [14, 27],
  'AI Agent': [8, 19],
  로보택시: [6, 13],
  전기차: [15, 16],
  '생성형 AI': [12, 14],
  '자동차보험 제도': [17, 9],
  손해율: [7, 8],
  'Physical AI': [2, 7],
  보험사기: [9, 5],
};
